### ISSUE TITLE
Incorect color

### ISSUE THREAD

**Issue by mrmykey** [sotrh/learn-wgpu#158]
I get the incorrect color after changing the pentagons color to `color: [35.0 / 255.0, 41.0 / 250.0, 46.0 / 255.0]` in `code/beginner/tutorial4-buffer` tutorial.

Expected color:
<img src="https://i.imgur.com/63EYe57.png" width="400" height="400">

Result:
![result](https://i.imgur.com/N7A2Kxk.png)

**Comment by sotrh** [comment]
I'm not an expert in color correction, so asking how to get accurate colors here won't do you much good. The folks at https://app.element.io/#/room/#wgpu:matrix.org would probably be more help.

**Comment by FrankenApps** [comment]
I am pretty sure this is because the colors are expected to be in sRGB like for example the `COLOR_0` attribute in GLTF. 
You can do an approximate transformation using for example
```rust
(35.0 / 255.0).powf(2.2)
```
unfortunately `powf()` is not a `const` function, so this can not be evaluated at compile time. When you calculate the transformation yourself, you get:
```rust
// #23292e corresponds to RGB(35, 41, 46), which can approximately be transformed like this
const MY_COLOR: [f32; 3] = [
    0.01266372003158210056121315133016, //(35.0f32 / 255.0f32).powf(2.2f32),
    0.017936433339950234462619470871186, //(41.0f32 / 255.0f32).powf(2.2f32),
    0.023103556157921445128315663554182, //(46.0f32 / 255.0f32).powf(2.2f32),
];
```
which results in 
![screenshot](https://user-images.githubusercontent.com/17967303/115507957-11500280-a27d-11eb-834c-8b97b8d3eac2.png)

As you can see, it is still not matching perfectly, but the visible difference is gone in my opinion. I do however not know, why the color is 4-6 units darker now. So that might need some further investigation...
