### ISSUE TITLE
Migrate to 0.8

### ISSUE THREAD

**Issue by sotrh** [sotrh/learn-wgpu#167]
# Core tasks
- [x] Migrate tutorial code
- [x] Migrate showcases
- [x] Add link to wasm compile steps
- [x] Add link to element/matrix chat room
# Bonus tasks
- [x] Evaluate switch to WGSL
- [ ] Test out wasm build on tutorial 5

**Comment by ColdIce1605** [comment]
About switching to WGSL. I've been translating the glsl code to wgsl and its possible and would remove shaderc, I got couldn't get it past the instancing part of it.

**Comment by sotrh** [comment]
I've translated tutorial 9's glsl to wgsl to debug https://github.com/gfx-rs/wgpu/issues/1360. You handle instancing data in the same way as regular vertex data. The codes on the 0.8 branch https://github.com/sotrh/learn-wgpu/blob/0.8/code/beginner/tutorial9-models/src/shader.wgsl

**Comment by ColdIce1605** [comment]
range_size 18 must be multiple of 4
still getting the same runtime error :|

**Comment by ColdIce1605** [comment]
well I did something as its working now

**Comment by sotrh** [comment]
If you're using an index buffer with `u16`, you'll need to add a padding `u16` if you have an odd number of indices.

**Comment by ifsheldon** [comment]
I am now walking through the tutorial using wgpu-rs 0.8, and I saw some API changes. The changes I saw until now are:
* `adapter.get_swap_chain_preferred_format()` now returns an Option
* `wgpu::PrimitiveState` adds two more attributes, which are `clamp_depth` and `conservative`
* `wgpu::PrimitiveState`'s cull_mode now takes `Option<Face>` instead of `CullMode`
* `wgpu::ColorTargetState` now no longer has the fields `alpha_blend` and `color_blend` but `blend` which is `Option<BlendState>`

I see in the branch 0.8, there are still some legacy APIs that haven't been changed, hope the above incomplete summary could be helpful

**Comment by sotrh** [comment]
Resolved in #177
