### ISSUE TITLE
Questions for Uniforms

### ISSUE THREAD

**Issue by ifsheldon** [sotrh/learn-wgpu#175]
I have several questions after walking through the chapter about uniforms. I think answers to these questions are details of uniforms, which you may consider adding to this chapter.

* Can we not create a separate uniform bind group and use existing texture bind group instead? I can see why you want to separate these two, but I am just curious.
* Can we not create a  `Uniforms` struct and do something old-school? like not using a struct of uniforms in shaders but using individual uniform variables like below. If we can, how can we set the `binding`s?
  ```glsl
  //layout(set=1, binding=0)
  //uniform Uniforms{
  //    mat4 u_view_proj;
  //    mat4 another_mat;
  //};
  // instead we do something old-school as in OpenGL
  layout(set=1, binding = 0) uniform mat4 u_view_proj;
  layout(set=1, binding = ?) uniform mat4 another_mat; // binding should still be 0?
  ```
* It seems the requirements to be `bytemuck::Pod` is very restrictive. We cannot have any paddings in a struct, which means something like `struct Foo {a : [f32;4], b : f32}` is prohibited. So, how can we deal with that? I see #109 is somewhat related to this question. Should we just use the crate mentioned in that issue?

**Comment by sotrh** [comment]
If I understand your first question you're asking why we can't lump the camera uniforms in with the texture uniforms? You absolutely can do that, but that would mean that if you want to use a model with different textures, you'd need to include the camera uniforms as well. It's not that big a deal, but it's a thing.

The answer to your second question is maybe, but the binding number would likely need to change meaning you'd need to create multiple bindings on the same uniform buffer in the bind group. If you use the same binding number WGPU will use the data at that binding and simply treat it as different data (assuming validation doesn't get upset at you).

"We cannot have any paddings in a struct" You can have padding fields with `bytemuck`. The issue is more that uniforms have a 16 byte alignment requirement. The crate mentioned in the issue you referenced seems pretty good. It may solve any alignment issues you've been having.

**Comment by ifsheldon** [comment]
Oh I see, thanks! So, in question 2, if we need to do something old-school, we will need to create multiple `Buffer`s that are bound differently, which is not as convenient as using a struct
