### ISSUE TITLE
The depth buffer is... correct

### ISSUE THREAD

**Issue by Onirik79** [sotrh/learn-wgpu#239]
I just finished the tutorial on instancing.
I was about to switch to the one about The Depth Buffer, but I noticed that the tree textures are already drawn correctly.
I suspect it's a feature of wgpu 0.10, and maybe this line in particular:

aspect: wgpu::TextureAspect::All,

but I don't have the knowledge to know for sure.

![instancing](https://user-images.githubusercontent.com/12321983/133938493-ee7858a9-27cc-404f-b829-03eb91b89c4e.png)
.

**Comment by sotrh** [comment]
It's not due to `wgpu::TextureAspect` as [that refers to the kind of data that the texture holds](https://docs.rs/wgpu/0.10.1/wgpu/enum.TextureAspect.html). For whatever reason the scene is rendering in a different order than when I made the tutorial initially. You can see the issue crop up if you view things from a different angle.

![depth_problems](https://user-images.githubusercontent.com/7904656/133940824-ac32e0b7-4fbd-4e14-9abc-37dc1a5b5f61.png)

I'll update the tutorial to comment on this.
