### ISSUE TITLE
Tutorial 4: Pod and Zeroable implementation for Vertex redundant and causes errors?

### ISSUE THREAD

**Issue by Newbytee** [sotrh/learn-wgpu#265]
I'm following tutorial 4, and I got to the point where you're told to add Pod and Zeroable implementations for Vertex. However, when I do this, I get the following error:

```
error[E0119]: conflicting implementations of trait `bytemuck::Zeroable` for type `Vertex`
  --> src/main.rs:19:45
   |
19 | #[derive(Copy, Clone, Debug, bytemuck::Pod, bytemuck::Zeroable)]
   |                                             ^^^^^^^^^^^^^^^^^^ conflicting implementation for `Vertex`
...
26 | unsafe impl bytemuck::Zeroable for Vertex {}
   | ----------------------------------------- first implementation here
   |
   = note: this error originates in the derive macro `bytemuck::Zeroable` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0119]: conflicting implementations of trait `bytemuck::Pod` for type `Vertex`
  --> src/main.rs:19:30
   |
19 | #[derive(Copy, Clone, Debug, bytemuck::Pod, bytemuck::Zeroable)]
   |                              ^^^^^^^^^^^^^ conflicting implementation for `Vertex`
...
25 | unsafe impl bytemuck::Pod for Vertex {}
   | ------------------------------------ first implementation here
   |
   = note: this error originates in the derive macro `bytemuck::Pod` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0119`.
error: could not compile `finite-water` due to 2 previous errors
```

Removing the empty implementations seems to fix it and I don't get any errors. However, I'm not sure if this is the solution or just a workaround, so I'm making this issue instead of a pull request.

**Comment by CatCode79** [comment]
You probably mean this part here:

```If your struct includes types that don't implement Pod and Zeroable Pod and Zeroable, you'll need to implement these traits manually. These traits don't require us to implement any methods, so we just need to use the following to get our code to work. [...]```

if you notice the [original text](https://sotrh.github.io/learn-wgpu/beginner/tutorial4-buffer/#what-is-a-buffer) is in a darker box to indicate that it is a clarification, in the tutorial code those extra lines are not needed.

What is said is that in your personal code you may happen to create structs (like a Mesh for example) that contain types that do not implement Pod and Zeroable.
In this case it is not possible to automatically derive the traits Pod and Zeroable.
If for these types it is not possible to implement these traits (because imported externally from another lib for example, or you don't want to implement them for design choices) then you are obliged to implement the Pod and Zeroable traits by hand by writing the two unsafe functions (and probably also containing significant code and not only empty brackets).

**Comment by Newbytee** [comment]
Okay, got it. Thanks!
