### ISSUE TITLE
Please consider leaving one example of using SPIR-V

### ISSUE THREAD

**Issue by ricardoalcantara** [sotrh/learn-wgpu#275]
Although there's WGSL It would be nice to have such a example.

**Comment by sotrh** [comment]
That would make sense. I'm thinking of having an example of using Naga directly

**Comment by sotrh** [comment]
So it's come to my attention that SPIR-V is not part of the WebGPU specification, and support for it is not guaranteed on all platforms, and may be removed. Because of this I've decided to close this issue.

I'll keep the demo's that use SPIR-V for now, but I'll likely have to migrated them to WGSL if/when SPIR-V is removed from wgpu.

**Comment by ricardoalcantara** [comment]
I understand your decision, for me it's very unfortunate, all projects I have checked that uses wgpu uses SPIR-V, Bevy for example uses SPIR-V, I my self changed to use SPIR-V too, for me dropping SPIR-V will be a big shoot in the foot, if they do probably most uses will leave it behind. Thanks for you time!
