### ISSUE TITLE
Possible structure adjustments?

### ISSUE THREAD

**Issue by edap** [sotrh/learn-wgpu#284]
Hello, many thanks for this tutorial, I have found it really helpful.
I think that there are a couple of places where the structure could be improved. More specifically:

1) Expand a bit the introduction, explaining what WebGPU is and why it is a big deal. I think it may have sense to highlight the fact that, in contrast to webGL or openGL, WebGPU is stateless, you first prepare the pipeline, and then you execute it. Of course it is obvious for a Metal or Vulkan user, but I think it can be helpful for the people coming from openGL or webgl.
2) I find it a bit confusing to talk about the pipeline without having vertices to render. What about introducing the vertices and the colors first and then how to shade them? In general, I think it would have been easier for me to follow this tutorial if it would have been structured in this order: 1)Intro 2) Get a window showing and get a device back 3) The surface chapter 4) Resource initialization, vertex and index buffer,  shaders 5)Pipeline layout 6) Commands encoder and render to the frame.

Again, thanks for your effort in writing this tutorial ;)

**Comment by sotrh** [comment]
Number 1 I definitely agree with. As far as number 2 goes, I structured things in this way because I wanted each tutorial to have visible progress. A user going through the tutorial would be able to see results at each step.

I could probably stand to go into vertices a little more, but I think I'll still leave buffers in their own section.

**Comment by edap** [comment]
yes, I totally understand. Thanks again for this great tutorial ;)
