### ISSUE TITLE
Lighting: Normal matrix is not required

### ISSUE THREAD

**Issue by julhe** [sotrh/learn-wgpu#337]
I'm working trough this great tutorial and noticed the introduction of a normal matrix (https://sotrh.github.io/learn-wgpu/intermediate/tutorial10-lighting/). This is not needed as one can simply use the model matrix to obtain the world-space normal as follows:
```GLSL
 out.world_normal = (model_matrix * vec4<f32>(model.normal, 0.0)).xyz; 
``` 

The reason this works is that the W component can be imagined as a kind of switch whether a transformation should include translation (1.0) or not (0.0). So effectively, we are still rotation and scaling the vector but not moving it. The normal needs to be normalized now trough, as any scaling would make it non-unit.

**Comment by sotrh** [comment]
The reason I don't use the `model_matrix` is because of the scaling isn't guaranteed to be uniform.  The normal would be skewed even if you normalize it afterward as you can see in this image ![](https://learnopengl.com/img/lighting/basic_lighting_normal_transformation.png)
If you  only allow uniform scaling, this isn't an issue and you can use the `model_matrix`, but if you will need to calculate the `normal_matrix`.
