### ISSUE TITLE
Padding in Working with Lights chapter

### ISSUE THREAD

**Issue by pintariching** [sotrh/learn-wgpu#459]
At the very top in the struct `LightUniform`, is the `_padding` field required? I think somewhere in the tutorial it says that `wgpu` automatically pads the struct, for example in the previous tutorial Model Loading, the struct `ModelVertex` doesn't have any padding, even though it looks like:
```rust
pub struct ModelVertex {
    pub position: [f32; 3],
    pub tex_coords: [f32; 2],
    pub normal: [f32; 3],
}
```

**Comment by sotrh** [comment]
`ModelVertex` doesn't need padding because it's only used in a vertex buffer and you have to specify the [VertexBufferLayout](https://docs.rs/wgpu/latest/wgpu/struct.VertexBufferLayout.html) for those. Uniform layout is a special case and it does require padding. By default uniform blocks use the `std140` alignment standard. You can read about alignment in [the wgpu spec](https://www.w3.org/TR/WGSL/#alignment-and-size), and I have started a [write up](https://sotrh.github.io/learn-wgpu/showcase/alignment/#alignment-of-uniform-and-storage-buffers) discussing in more detail.

From what I've read the reasoning this is performance. Rather than query the offsets for all the fields, the gpu simply expects fields to be at certain locations in memory. It takes whatever data is at that memory location and sends it to the shader. This means that if your struct is not padded correctly your shader will be pulling from the wrong parts of the struct. If `ModelVertex` were used as a uniform buffer `position` would overlap `tex_coords` in the shader meaning that `tex_coords.x` in the shader would map to `tex_coords[1]` in Rust.
