### ISSUE TITLE
 Why is the triangle color a rainbow ?

### ISSUE THREAD

**Issue by pythops** [sotrh/learn-wgpu#497]
In this section https://sotrh.github.io/learn-wgpu/beginner/tutorial4-buffer/#so-what-do-i-do-with-it ? 

is there a way to have access to every pixel coordinates inside the triangle to setup a custom color based on those coordinates ?

**Comment by sotrh** [comment]
The triangle is a rainbow because the GPU interpolates the values between the vertices in a process known as rasterization.

As far as getting access to the pixel coordinate inside the triangle you can use the `@builtin(position)` decorator on a `vec4` to get the pixels coordinates in screen space. It's basically the same as `gl_FragPosition` in OpenGL.

**Comment by pythops** [comment]
when using `@builtin(position)` as input for the fragment shader, what's the coordinates system we're getting there ? is it possible to transform it in clip space ?

**Comment by sotrh** [comment]
The coordinate system of `@builtin(position)` is in screen space, or in other words it uses the pixel coordinates of the viewport. You can transform them back to clip space, but it's simpler to just pass the clip space coords into the fragment shader from the vertex shader.

**Comment by sotrh** [comment]
For a little more context in the `@builtin(position)`, the top left corner of the viewport is (0,0) and the bottme right corner is (viewport_width, viewport_height). I believe the z component is the depth/array layer, though I'm not sure.

**Comment by pythops** [comment]
Thanks so much for your explanations :pray:
