### ISSUE TITLE
Panic when loading .obj without normals.

### ISSUE THREAD

**Issue by tmff** [sotrh/learn-wgpu#518]
In load_model, it is presumed that the mesh has normal's. If a model is loaded which doesn't have them it panics with an out of bounds exception.
```
let vertices = (0..m.mesh.positions.len() / 3)
                .map(|i| {
                    if m.mesh.normals.is_empty(){
                        model::ModelVertex {
                            position: [
                                m.mesh.positions[i * 3],
                                m.mesh.positions[i * 3 + 1],
                                m.mesh.positions[i * 3 + 2],
                            ],
                            tex_coords: [m.mesh.texcoords[i * 2], 1.0 - m.mesh.texcoords[i * 2 + 1]],
                            normal: [0.0, 0.0, 0.0],
                        }
                    }else{
                        model::ModelVertex {
                            position: [
                                m.mesh.positions[i * 3],
                                m.mesh.positions[i * 3 + 1],
                                m.mesh.positions[i * 3 + 2],
                            ],
                            tex_coords: [m.mesh.texcoords[i * 2], 1.0 - m.mesh.texcoords[i * 2 + 1]],
                            normal: [
                                m.mesh.normals[i * 3],
                                m.mesh.normals[i * 3 + 1],
                                m.mesh.normals[i * 3 + 2],
                            ],
                        }
                    }
                })
                .collect::<Vec<_>>();
```
There is probably a more elegant way to do this but I am not the best with Rust.

**Comment by sotrh** [comment]
That's a perfectly fine way of doing it. There might be a way to do it with just iterators, but this is good enough. Mind making a PR?

**Comment by tmff** [comment]
Yeah will do.

**Comment by adamgerhant** [comment]
since the vertex normals are derived from the face normals, they can be calculated from just the positions and indices. Also, I found that vertex normals lead incorrect rendering when faces joined at a high angle, since the face and vertex normal would be significantly different. In order to solve this I seperated the mesh such that no vertices are reused, and each stores the normal for its face. I can adapt my code and make a PR request if that would be helpful.

![normal2](https://github.com/sotrh/learn-wgpu/assets/116332429/dc728b2e-4493-4bac-ba4e-cbc0d07b23dd)

![normal3](https://github.com/sotrh/learn-wgpu/assets/116332429/4617d1ad-bd92-48f8-9cb6-d9b287d99525)
